# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\家长H5\yadong.campus.clife.cn_家长H5_幼儿考勤.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseYadongCampusClifeCn家长H5幼儿考勤(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"username": ["16620847001"], "password": ["VUsFjBeODaABgu37tXzPbw=="]}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("家长H5_幼儿考勤")
        .variables(**{"host": "yadong.campus.clife.cn", "donainname": "yadong"})
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("家长H5_登陆")
            .post("https://$host/v1/web/eduaccount/sys/login")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Length": "78",
                    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
                    "Host": "$host",
                    "Origin": "https://$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .with_data(
                {
                    "systemCode": "h5garden",
                    "username": "$username",
                    "password": "$password",
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token1")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-列表收藏应用（账号收藏的应用）")
            .get("https://$host/v1/web/edudistrict/apps/personal")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("登录相关-获取身份列表(H5)")
            .get("https://$host/v1/web/eduaccount/user/h5/identitys")
            .with_params(**{"showMsgCount": "1", "systemCode": "h5garden"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("登录相关-切换身份")
            .post("https://$host/v1/web/eduaccount/sys/changeId")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Length": "52",
                    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
                    "Host": "$host",
                    "Origin": "https://$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .with_data(
                {
                    "domainName": "$donainname",
                    "studentId": "$studentId",
                    "userType": "2",
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token2")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("登录相关-获取身份列表(H5)")
            .get("https://$host/v1/web/eduaccount/user/h5/identitys")
            .with_params(**{"showMsgCount": "1", "systemCode": "h5garden"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token2",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-列表收藏应用（账号收藏的应用）")
            .get("https://$host/v1/web/edudistrict/apps/personal")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token2",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-推荐应用-全部应用（账号角色可用的应用，可识别账号收藏的应用）")
            .get("https://$host/v1/web/edudistrict/apps/org")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token2",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤花名册-详情")
            .get("https://$host/v1/web/edugarden/attendance/roster/get")
            .with_params(
                **{"date": "2021-04-07", "gradeId": "8", "studentId": "$studentId"}
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token2",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("出勤概况-查看人考勤状态")
            .get("https://$host/v1/web/edugarden/statistic/queryAll")
            .with_params(
                **{
                    "endDate": "2021-04-07",
                    "startDate": "2021-04-01",
                    "studentId": "$studentId",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "https://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token2",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseYadongCampusClifeCn家长H5幼儿考勤().test_start()
