# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\教师H5\yadongitest.icampus.clife.net_教师H5_职工考勤.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseYadongitestIcampusClifeNet教师H5职工考勤(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"validnum": ["1", "2", "3", "4", "5", "6", "8", "9"]})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("教师H5_职工考勤")
        .variables(
            **{
                "Protocol": "${ENV(Protocol)}",
                "host": "${ENV(HOST)}",
                "domainName": "${ENV(DONAIN_NAME)}",
            }
        )
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("教师H5_登陆")
            .post("$Protocol://$host/v1/web/eduaccount/sys/login")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "78",
                    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
                    "Host": "$host",
                    "Origin": "$Protocol://$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .with_data(
                {
                    "systemCode": "h5garden",
                    "password": "${ENV(GARDEN_PASSWORD)}",
                    "username": "${ENV(GARDEN_USERNAME)}",
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-列表收藏应用（账号收藏的应用）")
            .get("$Protocol://$host/v1/web/edudistrict/apps/personal")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("登录相关-获取身份列表(H5)")
            .get("$Protocol://$host/v1/web/eduaccount/user/h5/identitys")
            .with_params(**{"showMsgCount": "1", "systemCode": "h5garden"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-月度数据列表")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/monthDataList"
            )
            .with_params(
                **{
                    "endTime": "${get_date()}",
                    "startTime": "${get_date(-12)}",
                    "systemCode": "H5",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-日考勤详情")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/attendanceDayItem"
            )
            .with_params(
                **{
                    "endTime": "${get_date()}",
                    "startTime": "${get_date()}",
                    "systemCode": "H5",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-有数据得月份")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/getAttendanceYearItem"
            )
            .with_params(**{"systemCode": "H5", "year": "2021"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-人员考勤月汇总")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/attendanceMonthItem"
            )
            .with_params(
                **{
                    "endTime": "${get_date()}",
                    "startTime": "${get_date(-12)}",
                    "systemCode": "H5",
                    "valid": "$validnum",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$domainName",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseYadongitestIcampusClifeNet教师H5职工考勤().test_start()
