# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\教师H5\yadong.campus.clife.cn_教师H5_教职工考勤.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseYadongCampusClifeCn教师H5教职工考勤(HttpRunner):

    config = (
        Config("教师H5_教职工考勤")
        .variables(
            **{
                "Protocol": "${ENV(Protocol)}",
                "host": "${ENV(HOST)}",
                "donainname": "${ENV(DONAIN_NAME)}",
            }
        )
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("教师H5_登陆")
            .post("$Protocol://$host/v1/web/eduaccount/sys/login")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Length": "78",
                    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
                    "Host": "$host",
                    "Origin": "$Protocol://$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .with_data(
                {
                    "systemCode": "h5garden",
                    "username": "${ENV(GARDEN_USERNAME)}",
                    "password": "${ENV(GARDEN_PASSWORD)}",
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-列表收藏应用（账号收藏的应用）")
            .get("$Protocol://$host/v1/web/edudistrict/apps/personal")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("登录相关-获取身份列表(H5)")
            .get("$Protocol://$host/v1/web/eduaccount/user/h5/identitys")
            .with_params(**{"showMsgCount": "1", "systemCode": "h5garden"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("应用-推荐应用-全部应用（账号角色可用的应用，可识别账号收藏的应用）")
            .get("$Protocol://$host/v1/web/edudistrict/apps/org")
            .with_params(**{"platform": "2"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-月度数据列表")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/monthDataList"
            )
            .with_params(
                **{
                    "endTime": "2021-04-30",
                    "startTime": "2021-04-01",
                    "systemCode": "H5",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-日考勤详情")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/attendanceDayItem"
            )
            .with_params(
                **{
                    "endTime": "2021-04-06",
                    "staffId": "22002488967173",
                    "startTime": "2021-04-06",
                    "systemCode": "H5",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-人员考勤有数据的月份")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/getAttendanceYearItem"
            )
            .with_params(**{"systemCode": "H5", "year": "2021"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("考勤统计-人员考勤月汇总明细")
            .get(
                "$Protocol://$host/v1/web/edugarden/attendance/statistics/attendanceMonthItem"
            )
            .with_params(
                **{
                    "endTime": "2021-04-30",
                    "staffId": "22002488967173",
                    "startTime": "2021-04-01",
                    "systemCode": "H5",
                    "valid": "$valid",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json;charset=utf-8",
                    "Host": "$host",
                    "Referer": "$Protocol://$host/school/m/",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/12.0 Mobile/15A372 Safari/604.1",
                    "X-Access-Token": "$token",
                    "X-Requested-With": "XMLHttpRequest",
                    "domainName": "$donainname",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseYadongCampusClifeCn教师H5教职工考勤().test_start()
